// generated by Fast Light User Interface Designer (fluid) version 1.0402

#include "main.h"
#include "clsAppContext.h"
#include <FL/x.h>

static void cb_EIS(Fl_Double_Window*, clsAppContext* v) {
  v->cbClose();
}

static void cb_Close(Fl_Button*, clsAppContext* v) {
  v->cbClose();
}

static void cb_Coefficients(Fl_WgtTree* o, clsAppContext*) {
  //o->cbTree();
}

static void cb_4fileopen(Fl_Button*, clsAppContext* v) {
  v->cbLoadMod();
}

static void cb_4filesave(Fl_Button*, clsAppContext* v) {
  v->cbSaveMod();
}

static void cb_Store(Fl_Button*, clsAppContext* v) {
  v->cbStoreMOD();
}

static void cb_1(Fl_Round_Button* o, clsAppContext* v) {
  v->cbModSlot(1,o);
}

static void cb_2(Fl_Round_Button* o, clsAppContext* v) {
  v->cbModSlot(2,o);
}

static void cb_3(Fl_Round_Button* o, clsAppContext* v) {
  v->cbModSlot(3,o);
}

static void cb_Restore(Fl_Choice* o, clsAppContext* v) {
  v->cbReStoreMOD(o->value());
}

static void cb_Prepare(Fl_Button*, clsAppContext* v) {
  v->cbGenerateFTable();
}

static void cb_Calculate(Fl_Button*, clsAppContext* v) {
  v->cbGenerateModelOutput(0);
}

static void cb_Store1(Fl_Button*, clsAppContext* v) {
  v->cbStoreFTABLE();
}

static void cb_11(Fl_Round_Button* o, clsAppContext* v) {
  v->cbFTSlot(1,o);
}

static void cb_21(Fl_Round_Button* o, clsAppContext* v) {
  v->cbFTSlot(2,o);
}

static void cb_31(Fl_Round_Button* o, clsAppContext* v) {
  v->cbFTSlot(3,o);
}

static void cb_Plot(Fl_Choice* o, clsAppContext* v) {
  v->cbPlotFT(o->value());
}

static void cb_4filesave1(Fl_Button*, clsAppContext* v) {
  v->cbSaveFT();
}

static void cb_Orig(Fl_Button*, clsAppContext* v) {
  v->cbStoreOrigEISDF();
}

static void cb_Text(Fl_Button*, clsAppContext* v) {
  v->cbLoadFTable();
}

static Fl_Group *grp_datafile=(Fl_Group *)0;

static void cb_Calculate1(Fl_Button*, clsAppContext* v) {
  v->cbGenerateModelOutput(1);
}

static void cb_Load(Fl_Button*, clsAppContext* v) {
  v->cbLoadData();
}

static void cb_Store2(Fl_Button*, clsAppContext* v) {
  v->cbStoreEISDF();
}

static void cb_F(Fl_Check_Button* o, clsAppContext* v) {
  v->cbSvcTable("ch.eisdf.src",o->value());
}

static void cb_F1(Fl_Check_Button* o, clsAppContext* v) {
  v->cbSvcTable("ch.eisdf.src.ftbl",o->value());
}

static void cb_Operation(Fl_Choice* o, clsAppContext* v) {
  v->cbDataOp(o->value());
}

static void cb_12(Fl_Round_Button* o, clsAppContext* v) {
  v->cbEISlot(1,o);
}

static void cb_22(Fl_Round_Button* o, clsAppContext* v) {
  v->cbEISlot(2,o);
}

static void cb_32(Fl_Round_Button* o, clsAppContext* v) {
  v->cbEISlot(3,o);
}

static void cb_Plot1(Fl_Choice* o, clsAppContext* v) {
  v->cbPlotEISDF(o->value());
}

static void cb_Prepare1(Fl_Button*, clsAppContext* v) {
  v->cbPrepareEISDFTable();
}

static void cb_4filesave2(Fl_Button*, clsAppContext* v) {
  v->cbSaveEISDF();
}

static clsMetaDataTable *MetaDataTable=(clsMetaDataTable *)0;

static void cb_MetaDataTable(clsMetaDataTable*, void*) {
  MetaDataTable->tbl_callback();
}

static void cb_Add(Fl_Button*, clsMetaDataTable* v) {
  v->cbAddRow();
}

static void cb_Del(Fl_Button*, clsMetaDataTable* v) {
  v->cbDelRow();
}

static void cb_Clear(Fl_Button*, clsMetaDataTable* v) {
  v->cbClearAll();
}

static void cb_For(Fl_Button*, clsAppContext* v) {
  v->cbSetDRTTools();
}

static void cb_Clear1(Fl_Button*, clsAppContext* v) {
  v->cbClearAll();
}

static void cb_File(Fl_Button*, clsAppContext* v) {
  v->cbShowFnames();
}

int main(int argc, char **argv) {
  Fl_Double_Window* w;
  clsAppContext AppContext;
  Fl::scheme("gtk+");
  { Fl_Double_Window* o = new Fl_Double_Window(800, 600, "EIS generator & editor");
    w = o; (void)w;
    o->labelsize(16);
    o->callback((Fl_Callback*)cb_EIS, (void*)(&AppContext));
    o->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Button* o = new Fl_Button(690, 10, 100, 25, "Close");
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelcolor((Fl_Color)81);
      o->callback((Fl_Callback*)cb_Close, (void*)(&AppContext));
    } // Fl_Button* o
    { Fl_Tabs* o = new Fl_Tabs(5, 107, 795, 513);
      o->selection_color((Fl_Color)206);
      o->labelsize(18);
      { Fl_Group* o = new Fl_Group(15, 138, 775, 458, "Model");
        o->labelsize(18);
        o->hide();
        { Fl_WgtTree* o = new Fl_WgtTree(25, 170, 385, 410, "Coefficients");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color((Fl_Color)246);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(18);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->callback((Fl_Callback*)cb_Coefficients, (void*)(&AppContext));
          o->align(Fl_Align(FL_ALIGN_TOP));
          o->when(FL_WHEN_CHANGED);
          AppContext.RegisterWg("tree_eis",o);
          o->root_label("Elements");
        } // Fl_WgtTree* o
        { Fl_Button* o = new Fl_Button(430, 165, 40, 40, "@+4fileopen");
          o->tooltip("Load model");
          o->labelcolor((Fl_Color)221);
          o->callback((Fl_Callback*)cb_4fileopen, (void*)(&AppContext));
        } // Fl_Button* o
        { Fl_Button* o = new Fl_Button(475, 165, 40, 40, "@+4filesave");
          o->tooltip("Save model");
          o->labelcolor((Fl_Color)68);
          o->callback((Fl_Callback*)cb_4filesave, (void*)(&AppContext));
        } // Fl_Button* o
        { Fl_Button* o = new Fl_Button(480, 250, 85, 25, "Store @>");
          o->labeltype(FL_ENGRAVED_LABEL);
          o->labelsize(16);
          o->labelcolor((Fl_Color)187);
          o->callback((Fl_Callback*)cb_Store, (void*)(&AppContext));
        } // Fl_Button* o
        { Fl_Group* o = new Fl_Group(575, 245, 125, 90, "Slots");
          o->box(FL_GTK_DOWN_FRAME);
          o->labelsize(18);
          o->user_data((void*)(&AppContext));
          { Fl_Round_Button* o = new Fl_Round_Button(590, 255, 105, 20, "1");
            o->type(102);
            o->down_box(FL_ROUND_DOWN_BOX);
            o->labelsize(18);
            o->callback((Fl_Callback*)cb_1, (void*)(&AppContext));
            AppContext.RegisterWg("rb.mod.slot1",o);
          } // Fl_Round_Button* o
          { Fl_Round_Button* o = new Fl_Round_Button(590, 280, 105, 20, "2");
            o->type(102);
            o->down_box(FL_ROUND_DOWN_BOX);
            o->labelsize(18);
            o->callback((Fl_Callback*)cb_2, (void*)(&AppContext));
            AppContext.RegisterWg("rb.mod.slot2",o);
          } // Fl_Round_Button* o
          { Fl_Round_Button* o = new Fl_Round_Button(590, 305, 105, 20, "3");
            o->type(102);
            o->down_box(FL_ROUND_DOWN_BOX);
            o->labelsize(18);
            o->callback((Fl_Callback*)cb_3, (void*)(&AppContext));
            AppContext.RegisterWg("rb.mod.slot3",o);
          } // Fl_Round_Button* o
          AppContext.RegisterWg("grp.eisdf.slots",o);
          o->end();
        } // Fl_Group* o
        { Fl_Choice* o = new Fl_Choice(445, 310, 120, 25, "Restore");
          o->down_box(FL_GTK_DOWN_BOX);
          o->labelsize(18);
          o->textsize(18);
          o->callback((Fl_Callback*)cb_Restore, (void*)(&AppContext));
          o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          o->when(FL_WHEN_RELEASE_ALWAYS);
          AppContext.RegisterWg("ch.mod.restore",o);
        } // Fl_Choice* o
        { Fl_Float_Input* o = new Fl_Float_Input(435, 426, 170, 24, "Area");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(16);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->textsize(16);
          o->user_data((void*)(&AppContext));
          o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          o->when(FL_WHEN_RELEASE);
          AppContext.RegisterWg("inpf_Area",o);
        } // Fl_Float_Input* o
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(10, 145, 780, 450, "Frequency table");
        o->labelsize(18);
        { Fl_Group* o = new Fl_Group(50, 255, 220, 150, "Range:");
          o->box(FL_GTK_DOWN_FRAME);
          o->labelsize(16);
          { Fl_InputWithMenu* o = new Fl_InputWithMenu(70, 300, 170, 24);
            o->box(FL_DOWN_BOX);
            o->color(FL_BACKGROUND2_COLOR);
            o->selection_color(FL_SELECTION_COLOR);
            o->labeltype(FL_NORMAL_LABEL);
            o->labelfont(0);
            o->labelsize(16);
            o->labelcolor(FL_FOREGROUND_COLOR);
            o->textsize(16);
            o->textcolor((Fl_Color)4);
            o->user_data((void*)(&AppContext));
            o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            o->when(FL_WHEN_RELEASE);
            AppContext.RegisterWg("inpf_minFrq",o);
          } // Fl_InputWithMenu* o
          { Fl_InputWithMenu* o = new Fl_InputWithMenu(70, 372, 170, 24);
            o->box(FL_DOWN_BOX);
            o->color(FL_BACKGROUND2_COLOR);
            o->selection_color(FL_SELECTION_COLOR);
            o->labeltype(FL_NORMAL_LABEL);
            o->labelfont(0);
            o->labelsize(16);
            o->labelcolor(FL_FOREGROUND_COLOR);
            o->textsize(16);
            o->textcolor((Fl_Color)4);
            o->user_data((void*)(&AppContext));
            o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            o->when(FL_WHEN_RELEASE);
            AppContext.RegisterWg("inpf_maxFrq",o);
          } // Fl_InputWithMenu* o
          { Fl_Choice* o = new Fl_Choice(120, 279, 81, 20, "Min,");
            o->down_box(FL_BORDER_BOX);
            o->labelsize(18);
            o->textsize(18);
            o->user_data((void*)(&AppContext));
            AppContext.RegisterWg("ch_minFrqK",o);
          } // Fl_Choice* o
          { Fl_Choice* o = new Fl_Choice(120, 350, 81, 20, "Max,");
            o->down_box(FL_BORDER_BOX);
            o->labelsize(18);
            o->textsize(18);
            o->user_data((void*)(&AppContext));
            AppContext.RegisterWg("ch_maxFrqK",o);
          } // Fl_Choice* o
          o->end();
        } // Fl_Group* o
        { Fl_Int_Input* o = new Fl_Int_Input(55, 191, 90, 24, "Points/Decade");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(16);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->textsize(16);
          o->user_data((void*)(&AppContext));
          o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          o->when(FL_WHEN_RELEASE);
          AppContext.RegisterWg("inpi_ppd",o);
        } // Fl_Int_Input* o
        { Fl_Int_Input* o = new Fl_Int_Input(50, 446, 90, 24, "Points:");
          o->box(FL_DOWN_BOX);
          o->color(FL_BACKGROUND2_COLOR);
          o->selection_color(FL_SELECTION_COLOR);
          o->labeltype(FL_NORMAL_LABEL);
          o->labelfont(0);
          o->labelsize(16);
          o->labelcolor(FL_FOREGROUND_COLOR);
          o->textsize(16);
          o->user_data((void*)(&AppContext));
          o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          o->when(FL_WHEN_RELEASE);
          AppContext.RegisterWg("inpi_nPt",o);
        } // Fl_Int_Input* o
        { Fl_Button* o = new Fl_Button(175, 195, 105, 25, "Prepare Table");
          o->tooltip("Generate frequency table");
          o->labelcolor((Fl_Color)148);
          o->callback((Fl_Callback*)cb_Prepare, (void*)(&AppContext));
        } // Fl_Button* o
        { Fl_Button* o = new Fl_Button(300, 195, 85, 25, "Calculate");
          o->labeltype(FL_ENGRAVED_LABEL);
          o->labelsize(16);
          o->labelcolor(FL_SELECTION_COLOR);
          o->callback((Fl_Callback*)cb_Calculate, (void*)(&AppContext));
        } // Fl_Button* o
        { Fl_Button* o = new Fl_Button(415, 280, 85, 25, "@< Store");
          o->labeltype(FL_ENGRAVED_LABEL);
          o->labelsize(16);
          o->labelcolor((Fl_Color)187);
          o->callback((Fl_Callback*)cb_Store1, (void*)(&AppContext));
        } // Fl_Button* o
        { Fl_Group* o = new Fl_Group(285, 280, 125, 90, "Slots");
          o->box(FL_GTK_DOWN_FRAME);
          o->labelsize(18);
          o->user_data((void*)(&AppContext));
          { Fl_Round_Button* o = new Fl_Round_Button(300, 290, 82, 20, "1");
            o->type(102);
            o->down_box(FL_ROUND_DOWN_BOX);
            o->labelsize(18);
            o->callback((Fl_Callback*)cb_11, (void*)(&AppContext));
            AppContext.RegisterWg("rb.ftable.slot1",o);
          } // Fl_Round_Button* o
          { Fl_Round_Button* o = new Fl_Round_Button(300, 315, 82, 20, "2");
            o->type(102);
            o->down_box(FL_ROUND_DOWN_BOX);
            o->labelsize(18);
            o->callback((Fl_Callback*)cb_21, (void*)(&AppContext));
            AppContext.RegisterWg("rb.ftable.slot2",o);
          } // Fl_Round_Button* o
          { Fl_Round_Button* o = new Fl_Round_Button(300, 340, 82, 20, "3");
            o->type(102);
            o->down_box(FL_ROUND_DOWN_BOX);
            o->labelsize(18);
            o->callback((Fl_Callback*)cb_31, (void*)(&AppContext));
            AppContext.RegisterWg("rb.ftable.slot3",o);
          } // Fl_Round_Button* o
          AppContext.RegisterWg("grp.ftable.slots",o);
          o->end();
        } // Fl_Group* o
        { Fl_Choice* o = new Fl_Choice(290, 400, 120, 25, "Plot");
          o->down_box(FL_GTK_DOWN_BOX);
          o->labeltype(FL_ENGRAVED_LABEL);
          o->labelsize(18);
          o->labelcolor((Fl_Color)146);
          o->textsize(18);
          o->callback((Fl_Callback*)cb_Plot, (void*)(&AppContext));
          o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          o->when(FL_WHEN_RELEASE_ALWAYS);
          AppContext.RegisterWg("ch.ft.plot",o);
        } // Fl_Choice* o
        { Fl_Group* o = new Fl_Group(565, 300, 205, 140, "Output");
          o->box(FL_GTK_DOWN_FRAME);
          o->labelsize(18);
          { Fl_Choice* o = new Fl_Choice(575, 390, 120, 25, "Source");
            o->down_box(FL_GTK_DOWN_BOX);
            o->labeltype(FL_ENGRAVED_LABEL);
            o->labelsize(18);
            o->labelcolor((Fl_Color)146);
            o->textsize(18);
            o->user_data((void*)(&AppContext));
            o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            AppContext.RegisterWg("ch.ft.save.src",o);
          } // Fl_Choice* o
          { Fl_Choice* o = new Fl_Choice(575, 330, 120, 25, "Format");
            o->down_box(FL_GTK_DOWN_BOX);
            o->labeltype(FL_ENGRAVED_LABEL);
            o->labelsize(18);
            o->labelcolor((Fl_Color)146);
            o->textsize(18);
            o->user_data((void*)(&AppContext));
            o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            AppContext.RegisterWg("ch.ft.save.ft",o);
          } // Fl_Choice* o
          { Fl_Button* o = new Fl_Button(715, 340, 40, 40, "@+4filesave");
            o->tooltip("Save generated EIS data");
            o->labelcolor(FL_SELECTION_COLOR);
            o->callback((Fl_Callback*)cb_4filesave1, (void*)(&AppContext));
          } // Fl_Button* o
          o->end();
        } // Fl_Group* o
        { Fl_Button* o = new Fl_Button(420, 320, 75, 25, "@>  Orig");
          o->tooltip("Sent data from selected slot to \"orig\" register");
          o->labeltype(FL_ENGRAVED_LABEL);
          o->labelsize(16);
          o->labelcolor((Fl_Color)147);
          o->callback((Fl_Callback*)cb_Orig, (void*)(&AppContext));
        } // Fl_Button* o
        { Fl_Group* o = new Fl_Group(595, 165, 170, 95, "Load");
          o->box(FL_GTK_DOWN_FRAME);
          o->labelsize(18);
          { Fl_Button* o = new Fl_Button(650, 175, 60, 26, "Text");
            o->tooltip("Load frequency table from data file.");
            o->labeltype(FL_EMBOSSED_LABEL);
            o->labelcolor((Fl_Color)59);
            o->callback((Fl_Callback*)cb_Text, (void*)(&AppContext));
          } // Fl_Button* o
          o->end();
        } // Fl_Group* o
        o->end();
      } // Fl_Group* o
      { grp_datafile = new Fl_Group(10, 140, 790, 460, "Data File");
        grp_datafile->labelsize(18);
        grp_datafile->hide();
        { Fl_Group* o = new Fl_Group(40, 220, 220, 190, "Range:");
          o->box(FL_GTK_DOWN_FRAME);
          o->labelsize(16);
          o->deactivate();
          { Fl_Float_Input* o = new Fl_Float_Input(60, 305, 170, 24);
            o->box(FL_DOWN_BOX);
            o->color(FL_BACKGROUND2_COLOR);
            o->selection_color(FL_SELECTION_COLOR);
            o->labeltype(FL_NORMAL_LABEL);
            o->labelfont(0);
            o->labelsize(16);
            o->labelcolor(FL_FOREGROUND_COLOR);
            o->textsize(16);
            o->user_data((void*)(&AppContext));
            o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            o->when(FL_WHEN_RELEASE);
            AppContext.RegisterWg("inpf.eisdf.minf",o);
          } // Fl_Float_Input* o
          { Fl_Float_Input* o = new Fl_Float_Input(60, 377, 170, 24);
            o->box(FL_DOWN_BOX);
            o->color(FL_BACKGROUND2_COLOR);
            o->selection_color(FL_SELECTION_COLOR);
            o->labeltype(FL_NORMAL_LABEL);
            o->labelfont(0);
            o->labelsize(16);
            o->labelcolor(FL_FOREGROUND_COLOR);
            o->textsize(16);
            o->user_data((void*)(&AppContext));
            o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            o->when(FL_WHEN_RELEASE);
            AppContext.RegisterWg("inpf.eisdf.maxf",o);
          } // Fl_Float_Input* o
          { Fl_Choice* o = new Fl_Choice(110, 284, 81, 20, "Min,");
            o->down_box(FL_BORDER_BOX);
            o->labelsize(18);
            o->textsize(18);
            o->user_data((void*)(&AppContext));
            AppContext.RegisterWg("ch.eisdf.minf",o);
          } // Fl_Choice* o
          { Fl_Choice* o = new Fl_Choice(110, 355, 81, 20, "Max,");
            o->down_box(FL_BORDER_BOX);
            o->labelsize(18);
            o->textsize(18);
            o->user_data((void*)(&AppContext));
            AppContext.RegisterWg("ch.eisdf.maxf",o);
          } // Fl_Choice* o
          { Fl_Check_Button* o = new Fl_Check_Button(80, 245, 82, 20, "Apply");
            o->down_box(FL_DOWN_BOX);
            o->labelsize(18);
            AppContext.RegisterWg("chb.eisdf.range",o);
          } // Fl_Check_Button* o
          o->end();
        } // Fl_Group* o
        { Fl_Button* o = new Fl_Button(390, 205, 85, 25, "Calculate");
          o->labeltype(FL_ENGRAVED_LABEL);
          o->labelsize(16);
          o->labelcolor(FL_SELECTION_COLOR);
          o->callback((Fl_Callback*)cb_Calculate1, (void*)(&AppContext));
        } // Fl_Button* o
        { Fl_Button* o = new Fl_Button(685, 155, 100, 30, "Load Data");
          o->tooltip("Load frequency table from data file.");
          o->labeltype(FL_EMBOSSED_LABEL);
          o->labelcolor((Fl_Color)59);
          o->callback((Fl_Callback*)cb_Load, (void*)(&AppContext));
        } // Fl_Button* o
        { Fl_Output* o = new Fl_Output(140, 427, 225, 31, "Points/ppd");
          o->labelsize(18);
          o->textsize(18);
          AppContext.RegisterWg("txout.eisdf.ppd",o);
        } // Fl_Output* o
        { Fl_Button* o = new Fl_Button(410, 265, 75, 25, "@<  Store");
          o->tooltip("Store temporary data in selected slot");
          o->labeltype(FL_ENGRAVED_LABEL);
          o->labelsize(16);
          o->labelcolor((Fl_Color)187);
          o->callback((Fl_Callback*)cb_Store2, (void*)(&AppContext));
        } // Fl_Button* o
        { Fl_Group* o = new Fl_Group(410, 400, 370, 185, "Operations");
          o->box(FL_GTK_DOWN_FRAME);
          o->labelsize(18);
          { Fl_Group* o = new Fl_Group(555, 430, 210, 150, "Data");
            o->box(FL_GTK_DOWN_FRAME);
            o->labelsize(18);
            { Fl_Value_Input* o = new Fl_Value_Input(671, 542, 90, 26, "Scale:");
              o->labelsize(16);
              o->minimum(1);
              o->maximum(100000);
              o->value(1);
              o->textsize(16);
              AppContext.RegisterWg("ch.eisdf.scale",o);
            } // Fl_Value_Input* o
            { Fl_Check_Button* o = new Fl_Check_Button(560, 455, 45, 25, "F.Table");
              o->down_box(FL_DOWN_BOX);
              o->labelsize(18);
              o->callback((Fl_Callback*)cb_F, (void*)(&AppContext));
              o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
              AppContext.RegisterWg("cb.eisdf.FtbSrc",o);
            } // Fl_Check_Button* o
            { Fl_Check_Button* o = new Fl_Check_Button(562, 506, 45, 25, "F.Table");
              o->down_box(FL_DOWN_BOX);
              o->value(1);
              o->labelsize(18);
              o->callback((Fl_Callback*)cb_F1, (void*)(&AppContext));
              o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
              AppContext.RegisterWg("cb.eisdf.FtbAd",o);
            } // Fl_Check_Button* o
            o->end();
          } // Fl_Group* o
          { Fl_Choice* o = new Fl_Choice(420, 435, 120, 25, "Operation");
            o->down_box(FL_GTK_DOWN_BOX);
            o->labeltype(FL_ENGRAVED_LABEL);
            o->labelsize(18);
            o->labelcolor((Fl_Color)146);
            o->textsize(18);
            o->callback((Fl_Callback*)cb_Operation, (void*)(&AppContext));
            o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            o->when(FL_WHEN_RELEASE_ALWAYS);
            AppContext.RegisterWg("ch.eisdf.dataop",o);
          } // Fl_Choice* o
          o->end();
        } // Fl_Group* o
        { Fl_Choice* o = new Fl_Choice(630, 455, 130, 25, "Source Table");
          o->down_box(FL_GTK_DOWN_BOX);
          o->labelsize(18);
          o->textsize(18);
          o->user_data((void*)(&AppContext));
          o->align(Fl_Align(FL_ALIGN_TOP_RIGHT));
          AppContext.RegisterWg("ch.eisdf.src",o);
        } // Fl_Choice* o
        { Fl_Choice* o = new Fl_Choice(630, 510, 130, 25, "Additional term ");
          o->down_box(FL_GTK_DOWN_BOX);
          o->labelsize(18);
          o->textsize(18);
          o->user_data((void*)(&AppContext));
          o->align(Fl_Align(FL_ALIGN_TOP_RIGHT));
          AppContext.RegisterWg("ch.eisdf.src.ftbl",o);
        } // Fl_Choice* o
        { Fl_Group* o = new Fl_Group(270, 265, 125, 90, "Slots");
          o->box(FL_GTK_DOWN_FRAME);
          o->labelsize(18);
          o->user_data((void*)(&AppContext));
          { Fl_Round_Button* o = new Fl_Round_Button(285, 275, 82, 20, "1");
            o->type(102);
            o->down_box(FL_ROUND_DOWN_BOX);
            o->labelsize(18);
            o->callback((Fl_Callback*)cb_12, (void*)(&AppContext));
            AppContext.RegisterWg("rb.eisdf.slot1",o);
          } // Fl_Round_Button* o
          { Fl_Round_Button* o = new Fl_Round_Button(285, 300, 82, 20, "2");
            o->type(102);
            o->down_box(FL_ROUND_DOWN_BOX);
            o->labelsize(18);
            o->callback((Fl_Callback*)cb_22, (void*)(&AppContext));
            AppContext.RegisterWg("rb.eisdf.slot2",o);
          } // Fl_Round_Button* o
          { Fl_Round_Button* o = new Fl_Round_Button(285, 325, 82, 20, "3");
            o->type(102);
            o->down_box(FL_ROUND_DOWN_BOX);
            o->labelsize(18);
            o->callback((Fl_Callback*)cb_32, (void*)(&AppContext));
            AppContext.RegisterWg("rb.eisdf.slot3",o);
          } // Fl_Round_Button* o
          AppContext.RegisterWg("grp.mod.slots",o);
          o->end();
        } // Fl_Group* o
        { Fl_Choice* o = new Fl_Choice(270, 385, 120, 25, "Plot");
          o->down_box(FL_GTK_DOWN_BOX);
          o->labeltype(FL_ENGRAVED_LABEL);
          o->labelsize(18);
          o->labelcolor((Fl_Color)146);
          o->textsize(18);
          o->callback((Fl_Callback*)cb_Plot1, (void*)(&AppContext));
          o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          o->when(FL_WHEN_RELEASE_ALWAYS);
          AppContext.RegisterWg("ch.eisdf.plot",o);
        } // Fl_Choice* o
        { Fl_Button* o = new Fl_Button(270, 205, 105, 25, "Prepare Table");
          o->tooltip("Generate frequency table");
          o->labelcolor((Fl_Color)148);
          o->callback((Fl_Callback*)cb_Prepare1, (void*)(&AppContext));
        } // Fl_Button* o
        { Fl_Group* o = new Fl_Group(560, 230, 205, 140, "Output");
          o->box(FL_GTK_DOWN_FRAME);
          o->labelsize(18);
          { Fl_Choice* o = new Fl_Choice(570, 320, 120, 25, "Source");
            o->down_box(FL_GTK_DOWN_BOX);
            o->labeltype(FL_ENGRAVED_LABEL);
            o->labelsize(18);
            o->labelcolor((Fl_Color)146);
            o->textsize(18);
            o->user_data((void*)(&AppContext));
            o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            AppContext.RegisterWg("ch.eisdf.save.src",o);
          } // Fl_Choice* o
          { Fl_Choice* o = new Fl_Choice(570, 260, 120, 25, "Format");
            o->down_box(FL_GTK_THIN_UP_BOX);
            o->labeltype(FL_ENGRAVED_LABEL);
            o->labelsize(18);
            o->labelcolor((Fl_Color)146);
            o->textsize(18);
            o->user_data((void*)(&AppContext));
            o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            AppContext.RegisterWg("ch.eisdf.save.ft",o);
          } // Fl_Choice* o
          { Fl_Button* o = new Fl_Button(710, 270, 40, 40, "@+4filesave");
            o->tooltip("Save generated EIS data");
            o->labelcolor(FL_SELECTION_COLOR);
            o->callback((Fl_Callback*)cb_4filesave2, (void*)(&AppContext));
          } // Fl_Button* o
          o->end();
        } // Fl_Group* o
        grp_datafile->end();
      } // Fl_Group* grp_datafile
      { Fl_Group* o = new Fl_Group(5, 140, 790, 450, "Meta Data");
        o->labelsize(18);
        o->hide();
        { clsMetaDataTable* o = MetaDataTable = new clsMetaDataTable(15, 225, 745, 310, "Meta Data");
          MetaDataTable->box(FL_THIN_DOWN_FRAME);
          MetaDataTable->color(FL_BACKGROUND_COLOR);
          MetaDataTable->selection_color(FL_BACKGROUND_COLOR);
          MetaDataTable->labeltype(FL_NORMAL_LABEL);
          MetaDataTable->labelfont(0);
          MetaDataTable->labelsize(14);
          MetaDataTable->labelcolor(FL_FOREGROUND_COLOR);
          MetaDataTable->callback((Fl_Callback*)cb_MetaDataTable, (void*)(&AppContext));
          MetaDataTable->align(Fl_Align(FL_ALIGN_TOP_LEFT));
          MetaDataTable->when(FL_WHEN_RELEASE);
          AppContext.RegisterWg("tbl_Meta_Ed",o);
          MetaDataTable->BindData(AppContext.MetaData);
          MetaDataTable->end();
        } // clsMetaDataTable* MetaDataTable
        { Fl_Button* o = new Fl_Button(250, 160, 100, 25, "Add row");
          o->labeltype(FL_ENGRAVED_LABEL);
          o->labelcolor((Fl_Color)4);
          o->callback((Fl_Callback*)cb_Add, (void*)(MetaDataTable));
        } // Fl_Button* o
        { Fl_Button* o = new Fl_Button(370, 160, 100, 25, "Del row");
          o->labeltype(FL_ENGRAVED_LABEL);
          o->labelcolor((Fl_Color)73);
          o->callback((Fl_Callback*)cb_Del, (void*)(MetaDataTable));
        } // Fl_Button* o
        { Fl_Button* o = new Fl_Button(490, 160, 100, 25, "Clear All");
          o->labeltype(FL_EMBOSSED_LABEL);
          o->labelcolor((Fl_Color)80);
          o->callback((Fl_Callback*)cb_Clear, (void*)(MetaDataTable));
        } // Fl_Button* o
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(15, 140, 775, 450, "Setup");
        o->labelsize(18);
        o->hide();
        { Fl_Group* o = new Fl_Group(55, 205, 315, 310, "Text Export");
          o->box(FL_GTK_DOWN_FRAME);
          o->labelsize(18);
          { Fl_Choice* o = new Fl_Choice(70, 235, 115, 25, "Locale:");
            o->down_box(FL_GTK_DOWN_BOX);
            o->labelsize(18);
            o->textsize(18);
            o->user_data((void*)(&AppContext));
            o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            AppContext.RegisterWg("ch_loc_csv",o);
          } // Fl_Choice* o
          { Fl_Check_Button* o = new Fl_Check_Button(70, 275, 140, 25, "Negative Z.Im");
            o->down_box(FL_DOWN_BOX);
            o->value(1);
            o->labelsize(18);
            o->user_data((void*)(&AppContext));
            AppContext.RegisterWg("cb_nzim_csv",o);
          } // Fl_Check_Button* o
          { Fl_Check_Button* o = new Fl_Check_Button(70, 305, 140, 25, "Column titles");
            o->down_box(FL_DOWN_BOX);
            o->labelsize(18);
            o->user_data((void*)(&AppContext));
            AppContext.RegisterWg("cb_col_csv",o);
          } // Fl_Check_Button* o
          { Fl_Check_Button* o = new Fl_Check_Button(70, 335, 165, 30, "<TAB> separator");
            o->down_box(FL_DOWN_BOX);
            o->labelsize(18);
            o->user_data((void*)(&AppContext));
            AppContext.RegisterWg("cb_tab_csv",o);
          } // Fl_Check_Button* o
          { Fl_Choice* o = new Fl_Choice(70, 450, 115, 25, "f sort order:");
            o->down_box(FL_GTK_DOWN_BOX);
            o->labelsize(18);
            o->textsize(18);
            o->user_data((void*)(&AppContext));
            o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            AppContext.RegisterWg("ch_fsort_csv",o);
          } // Fl_Choice* o
          { Fl_Check_Button* o = new Fl_Check_Button(70, 380, 165, 30, "Area-specific");
            o->down_box(FL_DOWN_BOX);
            o->value(1);
            o->labelsize(18);
            o->user_data((void*)(&AppContext));
            AppContext.RegisterWg("cb_asr_csv",o);
          } // Fl_Check_Button* o
          { Fl_Button* o = new Fl_Button(235, 240, 115, 25, "For DRTTools");
            o->labeltype(FL_ENGRAVED_LABEL);
            o->labelsize(16);
            o->labelcolor((Fl_Color)106);
            o->callback((Fl_Callback*)cb_For, (void*)(&AppContext));
          } // Fl_Button* o
          o->end();
        } // Fl_Group* o
        { Fl_Group* o = new Fl_Group(455, 230, 145, 105, "Load Text");
          o->box(FL_GTK_DOWN_BOX);
          o->labelsize(18);
          { Fl_Choice* o = new Fl_Choice(465, 260, 115, 25, "Locale:");
            o->tooltip("US- decimal <.>,\nEU- decimal <,>");
            o->down_box(FL_GTK_DOWN_BOX);
            o->labelsize(18);
            o->textsize(18);
            o->user_data((void*)(&AppContext));
            o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
            AppContext.RegisterWg("ch_loc_imptxt",o);
          } // Fl_Choice* o
          o->end();
        } // Fl_Group* o
        o->end();
      } // Fl_Group* o
      o->value(grp_datafile);
      o->end();
    } // Fl_Tabs* o
    { Fl_Multiline_Input* o = new Fl_Multiline_Input(25, 32, 655, 56, "Model:");
      o->box(FL_DOWN_BOX);
      o->color(FL_BACKGROUND2_COLOR);
      o->selection_color(FL_SELECTION_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->user_data((void*)(&AppContext));
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      o->when(FL_WHEN_RELEASE);
      AppContext.RegisterWg("ted_ExtMod",o);
    } // Fl_Multiline_Input* o
    { Fl_Button* o = new Fl_Button(690, 40, 100, 25, "Clear All");
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelcolor((Fl_Color)81);
      o->callback((Fl_Callback*)cb_Clear1, (void*)(&AppContext));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(690, 75, 100, 25, "File Names");
      o->labeltype(FL_EMBOSSED_LABEL);
      o->labelcolor((Fl_Color)67);
      o->callback((Fl_Callback*)cb_File, (void*)(&AppContext));
    } // Fl_Button* o
    AppContext.Win(o);
    AppContext.init_windows();
    o->end();
  } // Fl_Double_Window* o
  auto ic=LoadIconA(fl_display, MAKEINTRESOURCE(501));
  w->icons(ic,ic+5);
  w->show(argc, argv);
  return Fl::run();
}
