// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "form1.h"
#include "clsForm1Context.h"

static void cb_Plots(Fl_Double_Window*, clsForm1Context* v) {
  v->cbClose();
}

static void cb_Close(Fl_Button*, clsForm1Context* v) {
  v->cbClose();
}

static void cb_Plot(Fl_Choice* o, clsForm1Context* v) {
  v->cbSwitchPlot(o->value());
}

Fl_Double_Window* winit_form1() {
  Fl_Double_Window* w;
  static clsForm1Context Form1Context;
  { Fl_Double_Window* o = new Fl_Double_Window(900, 600, "Plots");
    w = o; if (w) {/* empty */}
    o->callback((Fl_Callback*)cb_Plots, (void*)(&Form1Context));
    o->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Button* o = new Fl_Button(780, 10, 100, 25, "Close");
      o->callback((Fl_Callback*)cb_Close, (void*)(&Form1Context));
      Form1Context.RegisterWg("btn_Close",o);
    } // Fl_Button* o
    { FL_PlotXY3_13::Fl_PlotXY3* o = new FL_PlotXY3_13::Fl_PlotXY3(65, 67, 775, 489, "Plot");
      o->box(FL_GTK_DOWN_BOX);
      o->color(FL_BACKGROUND2_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->user_data((void*)(&Form1Context));
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      o->when(FL_WHEN_RELEASE);
      Form1Context.RegisterWg("pltxy3_mod",o);
    } // FL_PlotXY3_13::Fl_PlotXY3* o
    { Fl_Choice* o = new Fl_Choice(460, 15, 175, 25, "Plot:");
      o->down_box(FL_BORDER_BOX);
      o->callback((Fl_Callback*)cb_Plot, (void*)(&Form1Context));
      Form1Context.RegisterWg("ch_mod_plt",o);
    } // Fl_Choice* o
    { Fl_Output* o = new Fl_Output(375, 566, 150, 24);
      o->box(FL_NO_BOX);
      o->user_data((void*)(&Form1Context));
      Form1Context.RegisterWg("outx_Xlab",o);
      o->value("X axis");
    } // Fl_Output* o
    { Fl_Rotated_Label* o = new Fl_Rotated_Label(20, 248, 35, 172);
      o->box(FL_NO_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->user_data((void*)(&Form1Context));
      o->align(Fl_Align(FL_ALIGN_CENTER));
      o->when(FL_WHEN_RELEASE);
      Form1Context.RegisterWg("rtl_YLax",o);
      o->angle(90);
    } // Fl_Rotated_Label* o
    { Fl_Rotated_Label* o = new Fl_Rotated_Label(845, 248, 35, 172);
      o->box(FL_NO_BOX);
      o->color(FL_BACKGROUND_COLOR);
      o->selection_color(FL_BACKGROUND_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(14);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->user_data((void*)(&Form1Context));
      o->align(Fl_Align(FL_ALIGN_CENTER));
      o->when(FL_WHEN_RELEASE);
      Form1Context.RegisterWg("rtl_YRax",o);
      o->angle(90);
    } // Fl_Rotated_Label* o
    Form1Context.Win(o);
    Form1Context.InitWidgets();
    o->end();
  } // Fl_Double_Window* o
  return w;
}
