// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef form1_h
#define form1_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Choice.H>
#include <FL/Fl_Output.H>
Fl_Double_Window* winit_form1();
#endif
