// generated by Fast Light User Interface Designer (fluid) version 1.0308

#include "formswc.h"
#include "clsFormSwcContext.h"

static void cb_Prepare(Fl_Double_Window*, clsFormSwcContext* v) {
  v->cbCancel();
}

static void cb_OK(Fl_Button*, clsFormSwcContext* v) {
  v->cbOK();
}

static void cb_Cancel(Fl_Button*, clsFormSwcContext* v) {
  v->cbCancel();
}

static void cb_All(Fl_Button*, clsFormSwcContext* v) {
  v->cbOnOff(true);
}

static void cb_All1(Fl_Button*, clsFormSwcContext* v) {
  v->cbOnOff(false);
}

Fl_Double_Window* winit_formswc() {
  Fl_Double_Window* w;
  static clsFormSwcContext FormSwcContext;
  { Fl_Double_Window* o = new Fl_Double_Window(300, 172, "Prepare data: ");
    w = o; if (w) {/* empty */}
    o->callback((Fl_Callback*)cb_Prepare, (void*)(&FormSwcContext));
    o->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_Button* o = new Fl_Button(185, 10, 100, 25, "OK");
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelcolor(FL_DARK_GREEN);
      o->callback((Fl_Callback*)cb_OK, (void*)(&FormSwcContext));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(185, 40, 100, 25, "Cancel");
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelcolor((Fl_Color)81);
      o->callback((Fl_Callback*)cb_Cancel, (void*)(&FormSwcContext));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(180, 105, 100, 25, "All On");
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelcolor((Fl_Color)80);
      o->callback((Fl_Callback*)cb_All, (void*)(&FormSwcContext));
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(180, 140, 100, 25, "All Off");
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelcolor((Fl_Color)4);
      o->callback((Fl_Callback*)cb_All1, (void*)(&FormSwcContext));
    } // Fl_Button* o
    { Fl_Group* o = new Fl_Group(10, 20, 150, 145, "Clear");
      o->box(FL_GTK_DOWN_FRAME);
      o->labeltype(FL_ENGRAVED_LABEL);
      o->labelsize(16);
      o->labelcolor((Fl_Color)80);
      { Fl_Check_Button* o = new Fl_Check_Button(30, 30, 100, 24, "DFile data");
        o->down_box(FL_DOWN_BOX);
        o->value(1);
        o->user_data((void*)(&FormSwcContext));
        FormSwcContext.RegisterWg("cb_DFd",o);
      } // Fl_Check_Button* o
      { Fl_Check_Button* o = new Fl_Check_Button(30, 56, 100, 24, "DFile meta data");
        o->down_box(FL_DOWN_BOX);
        o->value(1);
        o->user_data((void*)(&FormSwcContext));
        FormSwcContext.RegisterWg("cb_DFmd",o);
      } // Fl_Check_Button* o
      { Fl_Check_Button* o = new Fl_Check_Button(30, 81, 100, 24, "DFile registers");
        o->down_box(FL_DOWN_BOX);
        o->value(1);
        o->user_data((void*)(&FormSwcContext));
        FormSwcContext.RegisterWg("cb_DFrg",o);
      } // Fl_Check_Button* o
      { Fl_Check_Button* o = new Fl_Check_Button(30, 106, 100, 24, "FTable registers");
        o->down_box(FL_DOWN_BOX);
        o->value(1);
        o->user_data((void*)(&FormSwcContext));
        FormSwcContext.RegisterWg("cb_FTrg",o);
      } // Fl_Check_Button* o
      { Fl_Check_Button* o = new Fl_Check_Button(30, 131, 100, 24, "Model ");
        o->down_box(FL_DOWN_BOX);
        o->value(1);
        o->user_data((void*)(&FormSwcContext));
        FormSwcContext.RegisterWg("cb_Mod",o);
      } // Fl_Check_Button* o
      o->end();
    } // Fl_Group* o
    FormSwcContext.Win(o);
    o->end();
  } // Fl_Double_Window* o
  return w;
}
