// generated by Fast Light User Interface Designer (fluid) version 1.0308

#ifndef formswc_h
#define formswc_h
#include <FL/Fl.H>
#include <FL/Fl_Double_Window.H>
#include <FL/Fl_Button.H>
#include <FL/Fl_Group.H>
#include <FL/Fl_Check_Button.H>
Fl_Double_Window* winit_formswc();
#endif
