// generated by Fast Light User Interface Designer (fluid) version 1.0402

#include "ViewFNameForm.h"
#include <FL/x.h>

static void cb_EIS(Fl_Double_Window*, clsViewFNameCntx* v) {
  v->cbClose();
}

Fl_Double_Window* winit_viewfname() {
  Fl_Double_Window* w;
  static clsViewFNameCntx  ViewFNameCntx;
  { Fl_Double_Window* o = new Fl_Double_Window(783, 121, "EIS Data File Name");
    w = o; (void)w;
    o->callback((Fl_Callback*)cb_EIS, (void*)(&ViewFNameCntx));
    o->align(Fl_Align(FL_ALIGN_CLIP|FL_ALIGN_INSIDE));
    { Fl_OutputWithMenu* o = new Fl_OutputWithMenu(10, 18, 760, 27, "Data:");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)247);
      o->selection_color(FL_SELECTION_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(16);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->textsize(16);
      o->user_data((void*)(&ViewFNameCntx));
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      o->when(FL_WHEN_RELEASE);
      ViewFNameCntx.RegisterWg("txout_datfname",o);
      o->color(fl_rgb_color(190,240,255));
    } // Fl_OutputWithMenu* o
    { Fl_OutputWithMenu* o = new Fl_OutputWithMenu(10, 73, 760, 27, "Model:");
      o->box(FL_DOWN_BOX);
      o->color((Fl_Color)247);
      o->selection_color(FL_SELECTION_COLOR);
      o->labeltype(FL_NORMAL_LABEL);
      o->labelfont(0);
      o->labelsize(16);
      o->labelcolor(FL_FOREGROUND_COLOR);
      o->textsize(16);
      o->user_data((void*)(&ViewFNameCntx));
      o->align(Fl_Align(FL_ALIGN_TOP_LEFT));
      o->when(FL_WHEN_RELEASE);
      ViewFNameCntx.RegisterWg("txout_modfname",o);
      o->color(fl_rgb_color(190,240,255));
    } // Fl_OutputWithMenu* o
    ViewFNameCntx.Win(o);
    ViewFNameCntx.InitWidgets();
    o->end();
  } // Fl_Double_Window* o
  auto ic=LoadIconA(fl_display, MAKEINTRESOURCE(501));
  w->default_icons(ic,ic+5);
  w->show();
  return w;
}
