// generated by Fast Light User Interface Designer (fluid) version 1.0402

#ifndef ViewFNameForm_h
#define ViewFNameForm_h
#include <FL/Fl.H>
#include "clsViewFNameCntx.h"
#include <FL/Fl_Double_Window.H>
Fl_Double_Window* winit_viewfname();
#endif
